import React, { useEffect, useState } from 'react';
import { Lead, AuditReport } from '../types';
import { generateAudit } from '../services/geminiService';
import { X, Loader2, Printer, AlertTriangle, CheckCircle, BarChart3, ArrowRight, Copy, Check, Info } from 'lucide-react';

interface AuditModalProps {
  lead: Lead | null;
  isOpen: boolean;
  onClose: () => void;
  apiKey: string;
}

export const AuditModal: React.FC<AuditModalProps> = ({ lead, isOpen, onClose, apiKey }) => {
  const [report, setReport] = useState<AuditReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (isOpen && lead) {
      setLoading(true);
      setError(null);
      generateAudit(apiKey, lead)
        .then(setReport)
        .catch(err => setError(err.message))
        .finally(() => setLoading(false));
    } else {
      setReport(null);
    }
  }, [isOpen, lead, apiKey]);

  if (!isOpen || !lead) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    if (!report) return;
    
    const text = `
WEBSITE AUDIT REPORT FOR ${lead.name.toUpperCase()}
Date: ${new Date().toLocaleDateString()}
Website: ${lead.website || 'N/A'}
Overall Score: ${report.overallScore}/100

EXECUTIVE SUMMARY
${report.summary}

SCORE BREAKDOWN
${report.categories.map(c => `- ${c.name}: ${c.score}/10`).join('\n')}

CRITICAL ISSUES
${report.keyFindings.filter(f => f.type === 'issue').map(f => `[!] ${f.text}`).join('\n')}

POSITIVE SIGNALS
${report.keyFindings.filter(f => f.type === 'good').map(f => `[+] ${f.text}`).join('\n')}

TECHNICAL DETAILS
${report.technicalDetails.map(t => `- ${t.title}: ${t.value}`).join('\n')}

ACTION PLAN
${report.roadmap.map(p => `
PHASE: ${p.title}
${p.items.map(i => `- ${i}`).join('\n')}`).join('\n')}
    `.trim();
    
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getScoreColor = (score: number) => {
    if (score >= 70) return 'text-green-500 border-green-500'; // 70-100 (Skip/Good)
    if (score >= 50) return 'text-amber-500 border-amber-500'; // 50-70 (Low Priority)
    if (score >= 30) return 'text-orange-500 border-orange-500'; // 30-50 (Medium)
    return 'text-red-500 border-red-500'; // 0-30 (High Priority)
  };

  const getScoreBg = (score: number) => {
    if (score >= 70) return 'bg-green-500';
    if (score >= 50) return 'bg-amber-500';
    if (score >= 30) return 'bg-orange-500';
    return 'bg-red-500';
  };

  const getScoreInterpretation = (score: number) => {
    if (score <= 30) return { label: 'High Priority Lead', desc: 'Critical Issues. Easy to sell fixes.', color: 'text-red-600 bg-red-50 border-red-200' };
    if (score <= 50) return { label: 'Medium Priority', desc: 'Needs improvement. Good target.', color: 'text-orange-600 bg-orange-50 border-orange-200' };
    if (score <= 70) return { label: 'Low Priority', desc: 'Functional but could be better.', color: 'text-amber-600 bg-amber-50 border-amber-200' };
    return { label: 'Skip / Maintain', desc: 'Site is performing well.', color: 'text-green-600 bg-green-50 border-green-200' };
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/70 backdrop-blur-sm animate-in fade-in duration-200 overflow-y-auto print:p-0 print:bg-white print:static print:overflow-visible">
      <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-4xl min-h-[500px] overflow-hidden animate-in zoom-in-95 duration-200 border border-slate-200 dark:border-slate-800 print:shadow-none print:border-none print:w-full print:max-w-none print:rounded-none">
        
        {/* Header - Hidden on Print */}
        <div className="flex items-center justify-between p-6 border-b border-slate-100 dark:border-slate-800 print:hidden">
          <div className="flex items-center gap-2">
            <div className="bg-purple-100 dark:bg-purple-900/50 p-2 rounded-lg text-purple-600 dark:text-purple-400">
              <BarChart3 size={20} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Website & Business Audit</h3>
              <p className="text-sm text-slate-500 dark:text-slate-400">Generated by AI Agent</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={handleCopy}
              disabled={loading || !report}
              className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors text-slate-600 dark:text-slate-300 flex items-center gap-2 text-sm font-medium mr-2"
              title="Copy text for Canva/Docs"
            >
              {copied ? <Check size={18} className="text-green-500"/> : <Copy size={18} />}
              <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy Data'}</span>
            </button>
            <button 
              onClick={handlePrint}
              disabled={loading || !report}
              className="p-2 bg-slate-900 dark:bg-slate-100 hover:bg-slate-800 dark:hover:bg-white text-white dark:text-slate-900 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium"
            >
              <Printer size={18} /> Print PDF
            </button>
            <button onClick={onClose} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 ml-2">
              <X size={20} />
            </button>
          </div>
        </div>

        <div className="p-8 print:p-8 print:max-w-[210mm] print:mx-auto">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-24 space-y-4">
              <Loader2 className="animate-spin text-purple-600 dark:text-purple-400" size={48} />
              <div className="text-center">
                <p className="font-medium text-slate-900 dark:text-white">Analyzing Digital Presence...</p>
                <p className="text-sm text-slate-500 dark:text-slate-400">Checking SEO, Speed, Content & UX</p>
              </div>
            </div>
          ) : error ? (
            <div className="p-6 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-xl flex items-center gap-3">
              <AlertTriangle size={24} />
              <p>{error}</p>
            </div>
          ) : report ? (
            <div className="space-y-10 print:space-y-8">
              
              {/* Report Header */}
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 border-b border-slate-100 dark:border-slate-800 pb-8 print:pb-6 print:border-slate-300">
                <div>
                  <div className="hidden print:block mb-4 text-xs font-bold text-slate-400 tracking-widest uppercase">
                    Digital Performance Audit
                  </div>
                  <h1 className="text-3xl font-bold text-slate-900 dark:text-white print:text-black">{lead.name}</h1>
                  <p className="text-slate-500 dark:text-slate-400 print:text-slate-600 mt-1">{lead.website || "No Website Detected"}</p>
                  <p className="text-slate-500 dark:text-slate-400 print:text-slate-600 text-sm mt-1">Audit Date: {new Date().toLocaleDateString()}</p>
                  
                  {/* Status Badge */}
                  <div className={`mt-4 inline-flex items-center gap-2 px-3 py-1.5 rounded-full border text-sm font-semibold ${getScoreInterpretation(report.overallScore).color} print:border-slate-400 print:text-black print:bg-transparent`}>
                    <Info size={14} />
                    {getScoreInterpretation(report.overallScore).label}
                  </div>
                </div>
                
                <div className="flex items-center gap-4 bg-slate-50 dark:bg-slate-800/50 print:bg-transparent print:border print:border-slate-200 p-4 rounded-xl">
                   <div className={`relative w-20 h-20 flex items-center justify-center rounded-full border-4 ${getScoreColor(report.overallScore)}`}>
                      <span className={`text-2xl font-bold ${getScoreColor(report.overallScore).split(' ')[0]}`}>{report.overallScore}</span>
                   </div>
                   <div>
                     <p className="text-sm font-medium text-slate-500 dark:text-slate-400 print:text-slate-600">Overall Score</p>
                     <p className="text-xs text-slate-400 dark:text-slate-500 print:text-slate-500">{getScoreInterpretation(report.overallScore).desc}</p>
                   </div>
                </div>
              </div>

              {/* Executive Summary */}
              <section className="print:break-inside-avoid">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-3">Executive Summary</h4>
                <p className="text-slate-600 dark:text-slate-300 print:text-slate-700 leading-relaxed max-w-3xl">
                  {report.summary}
                </p>
              </section>

              {/* Category Breakdown */}
              <section className="print:break-inside-avoid">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-4">Category Breakdown</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4">
                  {report.categories.map((cat, idx) => (
                    <div key={idx} className="flex items-center gap-3">
                      <div className="flex-1">
                        <div className="flex justify-between mb-1">
                          <span className="text-sm font-medium text-slate-700 dark:text-slate-300 print:text-slate-700">{cat.name}</span>
                          <span className="text-sm font-bold text-slate-900 dark:text-white print:text-black">{cat.score}/10</span>
                        </div>
                        <div className="h-2 w-full bg-slate-100 dark:bg-slate-700 print:bg-slate-200 rounded-full overflow-hidden">
                          <div 
                            className={`h-full rounded-full ${getScoreBg(cat.score * 10)} print:print-color-adjust-exact`} 
                            style={{ width: `${cat.score * 10}%` }} 
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </section>

              {/* Key Findings */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 print:gap-6 print:break-inside-avoid">
                <section>
                  <h4 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-4">Critical Issues</h4>
                  <ul className="space-y-3">
                    {report.keyFindings.filter(f => f.type === 'issue').map((item, i) => (
                      <li key={i} className="flex items-start gap-3 text-sm text-slate-600 dark:text-slate-300 print:text-slate-700">
                        <AlertTriangle className="text-red-500 shrink-0 mt-0.5 print:text-red-600" size={16} />
                        <span>{item.text}</span>
                      </li>
                    ))}
                  </ul>
                </section>
                <section>
                  <h4 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-4">Positive Signals</h4>
                  <ul className="space-y-3">
                    {report.keyFindings.filter(f => f.type === 'good').map((item, i) => (
                      <li key={i} className="flex items-start gap-3 text-sm text-slate-600 dark:text-slate-300 print:text-slate-700">
                        <CheckCircle className="text-green-500 shrink-0 mt-0.5 print:text-green-600" size={16} />
                        <span>{item.text}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              </div>

              {/* Technical Details */}
              <section className="bg-slate-50 dark:bg-slate-800/30 p-6 rounded-xl print:bg-white print:p-0 print:border print:border-slate-200 print:break-inside-avoid">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-4 print:mt-4 print:mx-4">Technical Details</h4>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 print:p-4">
                  {report.technicalDetails.map((tech, idx) => (
                    <div key={idx} className="bg-white dark:bg-slate-800 p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm print:shadow-none print:border-slate-300">
                      <p className="text-xs text-slate-500 dark:text-slate-400 uppercase font-semibold">{tech.title}</p>
                      <div className="flex items-center gap-2 mt-1">
                         <div className={`w-2 h-2 rounded-full ${tech.status === 'pass' ? 'bg-green-500' : tech.status === 'fail' ? 'bg-red-500' : 'bg-amber-500'} print:print-color-adjust-exact`} />
                         <p className="font-bold text-slate-800 dark:text-slate-100 print:text-black">{tech.value}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </section>

              {/* Roadmap */}
              <section className="print:break-inside-avoid">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-6">Actionable Roadmap</h4>
                <div className="space-y-6">
                  {report.roadmap.map((phase, idx) => (
                    <div key={idx} className="relative pl-8 border-l-2 border-slate-200 dark:border-slate-700 print:border-slate-300">
                      <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-blue-600 border-4 border-white dark:border-slate-900 print:border-white print:print-color-adjust-exact" />
                      <h5 className="font-bold text-blue-900 dark:text-blue-300 text-sm uppercase tracking-wide mb-1 print:text-blue-800">{phase.phase}</h5>
                      <h6 className="font-bold text-slate-900 dark:text-white text-lg mb-2 print:text-black">{phase.title}</h6>
                      <ul className="space-y-1">
                        {phase.items.map((item, i) => (
                          <li key={i} className="text-slate-600 dark:text-slate-300 text-sm flex items-center gap-2 print:text-slate-700">
                             <ArrowRight size={12} className="text-blue-400" /> {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </section>

              <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-800 text-center hidden print:block">
                 <p className="text-xs text-slate-400 uppercase tracking-wider">Confidential Audit • Prepared for {lead.name}</p>
              </div>

            </div>
          ) : null}
        </div>
      </div>
      <style>{`
        @media print {
          @page {
            margin: 0;
            size: auto;
          }
          body {
            background: white;
          }
          /* Force standard colors for print */
          .print\\:print-color-adjust-exact {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
        }
      `}</style>
    </div>
  );
};